CREATE TABLE public.transactions (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	amount numeric(38, 2) NULL,
	description varchar(255) NULL,
	is_suspicious bool NULL,
	"location" varchar(255) NULL,
	transaction_date timestamp(6) NULL,
	user_id int8 NOT NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (id)
);


-- public.transactions foreign keys

ALTER TABLE public.transactions ADD CONSTRAINT fkqwv7rmvc8va8rep7piikrojds FOREIGN KEY (user_id) REFERENCES public.users(id);

INSERT INTO public.transactions (amount,description,is_suspicious,"location",transaction_date,user_id) VALUES
	 (20000.00,'makanan',false,'Jakarta','2025-08-01 07:54:30.123',1),
	 (100000.00,'penarikan',false,'Jakarta','2025-08-02 07:54:30.123',1),
	 (30000.00,'makanan',false,'Jakarta','2025-08-01 07:54:30.123',1),
	 (30000.00,'makanan',false,'Jakarta','2025-08-03 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-04 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-05 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-06 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-07 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-08 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-09 07:54:30.123',1);
INSERT INTO public.transactions (amount,description,is_suspicious,"location",transaction_date,user_id) VALUES
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-10 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-11 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-12 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-13 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-14 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-15 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-16 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-17 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-18 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-19 07:54:30.123',1);
INSERT INTO public.transactions (amount,description,is_suspicious,"location",transaction_date,user_id) VALUES
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-20 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-21 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-22 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-23 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-24 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-25 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-26 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-27 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-28 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-29 07:54:30.123',1);
INSERT INTO public.transactions (amount,description,is_suspicious,"location",transaction_date,user_id) VALUES
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-30 07:54:30.123',1),
	 (50000.00,'makanan dan minuman',false,'Jakarta','2025-08-31 07:54:30.123',1),
	 (150000.00,'Transfer',false,'Jakarta','2025-09-01 07:54:30.123',1),
	 (5000000.00,'Transfer',true,'Jakarta','2025-09-02 09:54:30.123',1),
	 (50000.00,'Makan dan minum',false,'Jakarta','2025-09-02 12:54:30.123',1),
	 (50000.00,'Makan dan minum',false,'Jakarta Selatan','2025-09-05 12:55:30.123',1),
	 (500000.00,'Penarikan',false,'Jakarta Barat','2025-09-05 13:01:30.123',1),
	 (1000000.00,'Penarikan',true,'Jakarta Barat','2025-09-05 13:02:53.123',1),
	 (40000.00,'Makan dan minum',false,'Jakarta Timur','2025-09-05 13:12:53.123',1),
	 (60000.00,'Makan dan minum',false,'Jakarta Selatan','2025-09-05 13:22:53.123',1);
INSERT INTO public.transactions (amount,description,is_suspicious,"location",transaction_date,user_id) VALUES
	 (50000.00,'Makan dan minum',false,'Jakarta Barat','2025-09-05 13:20:53.123',1),
	 (50000.00,'Makan dan minum',false,'Jakarta Pusat','2025-09-05 13:22:53.123',1),
	 (50000.00,'transfer',false,'Jakarta Pusat','2025-09-05 13:25:53.123',1),
	 (50000.00,'transfer',false,'Jakarta Pusat','2025-09-06 14:25:53.123',1),
	 (50000.00,'transfer',false,'Jakarta Barat','2025-09-06 14:30:53.123',1),
	 (50000.00,'transfer',false,'Jakarta Timur','2025-09-06 14:31:55.123',1),
	 (50000.00,'transfer',false,'Jakarta Timur','2025-09-06 14:31:55.123',1),
	 (60000.00,'Penarikan',false,'Jakarta Barat','2025-09-10 22:53:38.617',1),
	 (60000.00,'Penarikan',false,'Jakarta Barat','2025-09-10 22:53:40.421',1),
	 (60000.00,'Penarikan',false,'Jakarta Barat','2025-09-10 22:53:41.620',1);
INSERT INTO public.transactions (amount,description,is_suspicious,"location",transaction_date,user_id) VALUES
	 (60000.00,'Penarikan',false,'Jakarta Barat','2025-09-10 22:53:46.056',1),
	 (60000.00,'Penarikan',false,'Jakarta Selatan','2025-09-10 22:53:54.671',1),
	 (60000.00,'Penarikan',false,'Jakarta Selatan','2025-09-10 23:02:59.892',1),
	 (1000000.00,'Penarikan',true,'Jakarta Barat','2025-09-10 23:03:14.516',1),
	 (50000.00,'Makan dan minum',false,'Jakarta Selatan','2025-09-10 23:05:08.653',1),
	 (70000.00,'Makan dan minum',true,'Jakarta pusat','2025-09-10 23:05:22.854',1);
