CREATE TABLE public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	domicile varchar(255) NULL,
	email varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

INSERT INTO public.users (domicile,email,"name") VALUES
	 ('jakarta','dita@gmail.com','Dita');
